backend:
  name: git-gateway
  branch: master

media_folder: static/images/upload
public_folder: /images/upload
publish_mode: editorial_workflow

collections:
  - name: "meta"
    label: "Meta"
    delete: false
    editor:
      preview: false
    files:
      - name: "tags"
        label: "Tags"
        file: "meta/tags.yml"
        description: "List of tags"
        fields:
          - name: tags
            label: Tags
            label_singular: "Tag"
            widget: list
            fields:
              - label: "Slug"
                name: "slug"
                required: true
                pattern:
                  [
                    "^[a-z0-9]+(?:-[a-z0-9]+)*$",
                    "Um slug não pode ter espaços ou caracteres especiais",
                  ]
                widget: "string"
                hint: "A parte de um URL identifica a tag"
              - label: "Nome"
                name: "name"
                widget: "string"
                hint: "Nome da tag para exibição no site"

  - name: "posts"
    label: "Postagens"
    folder: "content/blog"
    extension: "md"
    format: "frontmatter"
    create: true
    slug: "{{slug}}"
    identifier_field: slug
    summary: "{{title}}"
    fields:
      - label: "Título"
        name: "title"
        widget: "string"
      - label: "Descrição"
        name: "description"
        widget: "string"
      - label: "Data Publicação"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD"
        dateFormat: "YYYY-MM-DD"
        timeFormat: false
      - label: Tags
        label_singular: "Tag"
        name: "tags"
        widget: list
        summary: "{{fields.tag}}"
        field:
          label: Tag
          name: tag
          widget: relation
          collection: "meta"
          file: "tags"
          searchFields:
            - "tags.*.name"
          displayFields:
            - "tags.*.name"
          valueField: "tags.*.slug"
      - label: "Texto"
        name: "body"
        widget: "markdown"
